name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if you have dependencies

    - name: SonarCloud Scan
      run: |
        # Replace placeholders with your SonarCloud project key and token
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=your_sonarcloud_token

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# Note: Add SONAR_TOKEN as a secret in your GitHub repository settings.
